on:
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: patch
          use_github_release_notes: true

  pull-request-quay:
    name: Create Pull Request against Quay repo
    runs-on: ubuntu-latest
    needs: [release-on-push]
    steps:
      - name: Check out Quay repo
        uses: actions/checkout@v3
        with:
          repository: quay/quay
      - name: Update the version in Quay Dockerfile
        run: sed -i "s/CONFIGTOOL_VERSION=v.*$/CONFIGTOOL_VERSION=${{ needs.release-on-push.outputs.tag_name }}/" Dockerfile
      - name: Create Pull Request Quay
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          title: "build(deps): bump config-tool to ${{ needs.release-on-push.outputs.tag_name }}"
          commit-message: "build(deps): bump config-tool to ${{ needs.release-on-push.outputs.tag_name }}"
          author: quay-devel <quay-devel@redhat.com>
          branch: quay/config-tool-pr
          delete-branch: true
          signoff: true
          body: Update config-tool to ${{ needs.release-on-push.outputs.tag_name }}
          committer: quay-devel <quay-devel@redhat.com>
